# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
jdk:
  - openjdk12
env:
  global:
    - CODECOV_TOKEN="a7f4a5c4-ba1f-42cb-9e74-556f3d25df78"

# используем режим обычного пользователя для сборки проекта.
sudo: false

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

# Отправлять уведомление на почтуyouremail@smtp.ru(Изменить на свою) если сборка упала
notifications:
  email:
    recipients:
      - t0l1k@mail.ru
    on_success: never # default: change
    on_failure: always # default: always


